# Generated by Django 4.2.29 on 2026-06-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="image",
            field=models.ImageField(blank=True, upload_to="skills/"),
        ),
    ]
